load_main_model: true
model:
  type: pyramid
  alpha: 200
  depth: 272
  bottleneck: true
dataset: cifar10
cutout: 16
batch: 32
gpus: 2
epoch: 1800
lr: 0.05
aug: randaugment
augmentation_search_space: wide_standard
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 5.0e-5
