model:
  type: wresnet28_10
dataset: svhncore
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
cutout: 16
batch: 128
gpus: 1
epoch: 200
lr: 0.001
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 5
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.005

