model:
  type: wresnet40_2
dataset: cifar100
aug: randaugment
randaug:
  N: 301
  M: 301   # from appendix
cutout: 16
batch: 128
gpus: 1
epoch: 200
lr: 0.1
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

